services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/tasks
  db:
    image: postgres:16.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasks
    volumes:
      - ./backend/init:/docker-entrypoint-initdb.d
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/package.json:/app/package.json
      - ./frontend/src:/app/src
